# Generated by Django 5.1.3 on 2024-11-28 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_truck_cuisine'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyschedule',
            unique_together={('date', 'location'), ('date', 'truck')},
        ),
    ]
